const storyInfo = {
	"general": {
		"mi": "Singular \"me.\"",
		"do": "Singular \"you.\"",
		"ko": "\"You\" in the sense that it makes the statement a command that the listener is intended to follow.",
		"ti": "\"This\" in the sense that you're demonstrating what you're talking about, and it's immediately present. If it were just, like, close, but not close enough that you expect \"ti\" to be immediately understood, you'd say \"ta\". If it were far away, you'd say \"tu\".",
		"miho": "\"We\" as in both you and me, and maybe others.",
		"no": "Zero.",
		"pa": "1",
		"re": "2",
		"ci": "3",
		"goi": "\"goi\" lets you, explicitly, write out what pronouns refer to.",
		"koha": "\"ko'a\" is a third-person pronoun in, like, the most extreme sense of the word. It can be he/she/it/they, singular, plural, whatever. It's entirely based on context <i>unless</i> you use \"goi\" to explicitly say what the pronoun refers to. \"ko'a\" is just one of them, there's ten in total, ko'a, ko'e, ko'i...",
		"i": "New sentence.",
		"ije": "New sentence continuing the same topic. It's not really necessary, but I like using it when sentences are clearly building off each other like this.",
		"be": "Directly stick the object after this into a verb.",
		"po": "That is specific to / belonging to",
		"je": "\"and\" in the sense that it continues the same topic.",
		"gihe": "\"and\" in the sense of doing one thing and also another thing.",
		"e": "\"and\" in the sense that these two nouns are being grouped together.",
		"giha": "\"or\" in the sense of doing either of two things, or possibly both things.",
		"poi": "For which this is true. This is much more restrictive than \"noi\" which is just, like, for which this <i>happens</i> to be true.",
		"keha": "When using \"poi\", it's sometimes useful to refer to the thing that the \"poi\" is stuck to the end of. \"ke'a\" always means \"the thing this relative clause is about.\"",
		"noi": "For which this is incidentally true. Often useful for epithets.",
		"kuho": "Ends the \"noi\" / \"poi\" from earlier.",
		"babo": "\"Then\", in the sense of doing one thing and then another. \"ba\" means \"future\" in the sense that it implies forward movement in time and \"bo\" is just to imply that whatever's after this takes place after whatever's before.",
		"co": "Modifies a verb similar to how adverbs work.",

		"lo": "The noun that does this verb. For example, \"kelci\" means \"to play with something\" so \"lo kelci\" means \"player.\" It doesn't say how many, but it does imply at least one.",
		"loi": "\"lo\" makes a noun out of a verb, and \"loi\" makes it a plural noun. If you want a noun that encompasses <i>all</i> of this thing, that's \"lo'i\".",
		"lohi": "The set of all things that do this verb.",
		"le": "\"The\" in the sense that what is being referred to is given by context somehow. \"that one.\"",
		"lei": "\"le\" but plural. Similar to english \"those\"",
		"la": "Proper noun-ifier. More specifically, this means \"the thing that's called...\" but the Eiffel Tower is the thing that's called Eiffel Tower.",
		"lai": "Proper noun-ifier but the i makes it plural. Specifically, \"lai\" means something close to \"the group of things referred to as...\"",
		"ro": "Each",
		"da": "This is a logically-quantified noun. Usually, you can just get away with saying \"everybody does (this)\" but in some cases, the person doing (this) appears somewhere inside of (this), and we need a way to quantify that single person, and not the set of all people. \"da\" does that job.",
		"lu": "Quotation.",
		"lihu": "End quotation.",
		"ku": "This says when a noun is over.",

		"cu": "\"cu\" means \"the subject of the sentence is over now. here comes the verb.\" which is usually not necessary.",
		"tohe": "The polar opposite of something. With this, not-down always means up, whereas with \"na\" not-down could be left, forward, back, nowhere at all, anything except up.",
		"na": "Not. This says a statement is not true.",
		"suho": "At least, in terms of numbers being greater than or equal to something.",
		"xu": "Signals that this statement is a true/false question.",

		"ba": "Future tense.",
		"pu": "Past tense.",
		"ca": "Present tense.",
		"ki": "Stick this at the end of a tense word to indicate that that tense is the new default until you say otherwise.",
		"ba2": "After (this thing happens). This can be thought of as saying \"in the future of (this), ...\"",
		"pu2": "Before (this thing happens). This can be thought of as saying \"in the past of (this), ...\"",
		"ca2": "During (this thing happening)",
		"bo": "Connect the surrounding things together. This is most often used with time indicators to say that this happened, then that happened, which is always implied, but \"babo\" is a common construction anyway.",
		"babo": "\"ba\" = future tense, \"bo\" = connect the surrounding things together. So, this construction connects the following to the future of the previous thing, which is like saying \"and then this happens.\" It's always implied that the arrow of time moves forward, but that's true in real life too, and people still say \"then\" to clarify.",

		"se": "Swap the subject and object of the following verb. \"dunda\" means \"to give something to someone,\" whereas \"se dunda\" means \"to be given by someone to someone.\" Less commonly, the word \"te\" can swap the subject with the <i>second</i> object, meaning \"te dunda\" means \"to be given something by someone.\"",
		"te": "Swap the subject and <i>second</i> object of the following verb. \"dunda\" means \"to give something to someone,\" whereas \"te dunda\" means \"to be given something from someone.\" It's not often very useful, because the words in lojban are all defined in what seems like the most often useful way. Even less often, you might want to use \"ve\" and \"xe\" to swap the subject with the third and fourth objects.",

		"nu": "The event of this happening.",
		"zuho": "The activity of this happening.",
		"ni": "The amount of this.",
		"ka": "The state of being this.",
		"duhu": "The relationship implied by this. Very useful for stuff like facts, like how \"cats always land on their feet\" is a fact, a relationship, and basically its own self-contained sentence.",
		"siho": "The concept of this.",
		"jei": "The truth value of this statement. It's most similar to english \"whether.\"",
		"kei": "Ends an event, or other kind of abstraction. Usually it's not necessary, but for complicated sentences it's a helpful indicator.",
		
		"ranmi": "Notably, this doesn't mean something that is legendary, it is specifically a legend. A more faithful translation might be \"ramy'inda\" or \"ramjerna\" (deserving of legend, kinda). Who give a shit, though.",
		"danlu": "Creature. Unfortunately, this comes with the implication that the creature is, like, not sentient, but then again, that's true in english too.",
		"creature": "Creature. Unfortunately, this comes with the implication that the creature is, like, not sentient, but then again, that's true in english too.",
		"instant": "\"sutmocmakfa\" = sutra (fast) + mokca (moment) + makfa (magic_ = fast momentary magic. I thought about just using the word for \"instant\" in lojban, but like, that's not a very good name.",
		"sorcery": "\"mocmakfa\" = mokca (moment) + makfa (magic) = momentary magic. It should be noted that \"momentary\" does not mean \"fast.\" That's \"sutra.\" This is magic that takes effect in a single moment.",
		"kakne": "Is able to do (this)",
		"kakne2": "Is able to do (this) under (these) conditions",
		"bradi": "Opponent. More specifically, it means \"to be an enemy of someone\"",
		"kelci": "Player. More specifically, it means \"to play with something,\" so \"lo kelci\" means \"the thing that plays with something\" which is a player.",
		"terxai": "\"xrani\" means \"to injure (some victim) in (some way)\" so when we combine that with \"te\" to swap the subject with that second object, the verb becomes \"to be damaged within (some victim) by (some damage-causing-event)\" which is what damage is. So \"terxai\" means damage.",
		"damba": "To Fight / Battle / Combat",
		"mulcabna": "To occur after something. Usually, I use this with \"se\" to turn the verb into \"to have x1 be followed by x2\" the same way mtg uses \"when x1, x2\"",
		"cpacu": "To obtain. In this context, I'm using it to mean \"draw\" because to draw cards you get 'em. Drawing them from your library is implied, just like it is in english.",
		"karda": "Card. This is one of very few cognates.",
		"card": "Card. This is one of very few cognates.",
		"gunta": "To attack (somebody)",
		"attack": "To attack (somebody)",
		"punji": "To put (something) into/onto (some place)",
		"cast": "\"mafpli\" = makfa (magic) + pilno (use) = use magic = to cast.",
		"exile": "\"dargau\" = darno (distant) + gasnu (to cause) = to cause something to become distant = exile, in mtg terms.",
		"spell": "\"mafru'e\" = makfa (magic) + pruce (process) = spell. There's an argument that it should be the reverse order.",
		"turn": "\"kelka'u\" = kelci (play) + kantu (small part) = a tsmall part of a game = a turn.",
		"power": "Strength / Power.",
		"token": "kelci (play) + sicni (token) = token (as in a game piece)",
		"create": "marji (stuff) + gasnu (cause) = to cause stuff = to create.",

		"graveyard": "\"mrofoi\" = morsi (dead) + foldi (field) = graveayrd. stuzi just means place.",
		"library": "\"ckusro\" = cukta (book) + sorcu (source) = library. stuzi just means place.",
		"exilezone": "\"dargau\" = darno (distant) + gasnu (to cause) = to cause something to become distant = exile, in mtg terms. stuzi just means place, which is why I've also added a stuzi to all the other zones.",

		"target": "It's really weird that in english we just imply an extra step to casting the spell merely by putting the word target in front of something. That's very difficult to do here. It's possible, but looks very confusing. Instead, I've just put all the targeting instructions explicitly at the start of the text.",

		"trigger": "Previously, I used \"se mulcabna\" to indicate triggered abilities. Holy shit is that not necessary. Like, <div class='row'><div class='col'>Pros:</div><div class='col'>Cons:</div><div class='row'><div class='col'>- It counts as a verb, so it's very useful to clearly define the relationship between trigger condition and effect.</div><div class='col'>- It requires the entire ability to be written out as a single sentence.<br>- It's incredibly cumbersome, and very confusing, to have an ability where person A does one thing and person B then does another thing.<br>- There's already a perfectly good tense marker for this in lojban.</div></div>",
		"combat-damage": "The way magic uses the term, \"combat\" is an adjective on the noun \"damage,\" but in lojban, everything's a verb, and the line between what should be written as an adjective or an adverb is fuzzy. I think \"combat kind of damage\" sounds weirder than \"damage in a combative way\" for this construction, so I used \"terxai co damba\" instead of \"damba terxai\".",
		"permanent": "\"vi'ordai\" = vitno (unmoving) + dacti (thing) = object that doesn't move = permanent, in mtg terms.",

		"ti2": "Look, magic has this weird fascination with writing the name of the card in the text box to indicate when it's referring to itself. I understand the reasoning, but I'm not gonna deal with that when writing this in another language. \"ti\" is a pronoun that means \"this thing right here\" and on these cards I'm using it to mean \"this object that the text is on\" which is a very specific meaning in mtg.",
	},
	"Spellweaver Volute": {
		"zuho1": "The activity of you casting the thing without paying its mana cost.",
		"zuho2": "The activity of paying its mana cost.",
		"nu1": "The event of you attaching this to another instant.",
		"nu2": "The event of you casting a sorcery spell.",
		"duhu1": "The predication (fact) that you cast the copy.",
		1: "\"mafru'ejivbu\" = makfa (magic) + pruce (process) + jivbu (weave) = (magic process) weave = spell weave. By default, these are grouped from the left like that.",
		2: "\"cakcurnu\" = calku (shell) + curnu (invertebrate animal, usually worm) = shelled worm-like invertebrate = mollusk, or snail.",
		3: "\"vi'ormakfa\" = vitno (permanent) + makfa (magic) = a magic that remains in existence = enchantment. I'm not happy with it either.",
		4: "\"sruri\" means \"to surround (something).\" I could stick a \"makfa\" in there to make it mean something like \"to magically surround,\" which is closer, but as you can see we've got enough makfa's already.",
		5: "\"mafyjo'e\" = makfa (magic) + jorne (to be connected to something) = enchant, in mtg terms.",
		6: "\"sutmocmakfa\" = sutra (fast) + mocka (moment) + makfa (magic) = fast momentary magic = instant. Technically, this is more like \"quick-moment magic\" (like the \"sutra\" modifies the \"mocka\", not the \"makfa\")",
		7: "To be inside of somewhere.",
		8: "\"mrofoi\" = morsi (dead) + foldi (field) = graveyard. \"stuzi\" just means \"place\" in the sense that the place doesn't move. Like a zone in a game.",
		9: "\"mafpli\" = makfa (magic) + pilno (to use) = to use magic = to cast a (something)",
		10: "\"mafru'e\" = makfa (magic) + pruce (process) = magic procss = spell.",
		11: "\"mocmakfa\" = mocka (moment) + makfa (magic) = momentary magic = sorcery, in mtg terms.",
		12: "\"fukygau\" = fukpi (to be a copy) + gasnu (cause) = to create a copy of something.",
		13: "\"mafyjo'e\" = makfa (magic) + jorne (to be connected to) = to enchant, in mtg terms. In this case, it's swapped with \"se\" so this means \"to be enchanted by\" instead.",
		14: "If this weren't here, this would say \"'this card' is also known as x1\" instead of \"'the card enchanted by this card' is also known as x1\".",
		15: "Able to do the thing after this. Here, the \"ca\" modifies it so it's clear you can just do this right now. Without the \"ca\" it would be like saying how \"birds can fly,\" like, just a broad, this is possible sorta thing.",
		16: "In a way that lacks paying its mana cost.",
		17: "To lack something.",
		18: "To pay some cost.",
		19: "\"mafnenlai\" = makfa (magic) + nejni (energy) + klani (quantity) = magic-energy amount. I personally would've just made it magic energy, but that's what's already in the dictionary. \"jdime\" just means price, or cost.",
		20: "To be a copy of something.",
		21: "If (this) predication is true, then (that) event happens. There's an optional third parameter if you want to add an else statement. Oh, programmers :)",
		22: "\"jornygau\" = jorne (to be connected to something) + gasnu (cause) = to cause something to be connected to something. This little \"add a gasnu\" construction happens a lot in lojban.",
		23: "To be not the same thing as (this). \"Other\" is a tricky concept in lojban.",
		24: "\"dargau\" = darno (to be distant) + gasnu (to cause) = to cause something to be removed = exile, in mtg terms. This little \"add a gasnu\" construction happens a lot in lojban.",
	},
	"Whims of the Fates": {
		1: "\"seljdi\" = se (swap the subject and object of the next verb) + djice (to make (some decision)) = \"to be a decision made by...\"",
		2: "\"dimna\" literally just means destiny. It does not imply that Fate is like, an agent that decides stuff here, like it does in greek myth and on the card.",
		3: "In this case, \"seldji\" already clearly says that the next noun is the thing that makes the decision. This \"be\" is not required, but it gets us closer to the wording of the actual card.",
		4: "\"mocmakfa\" = mocka (instantaneous, momentary) + makfa (magic) = magic that happens in a single moment = sorcery, in mtg terms. Notably, instantaneous doesn't mean \"fast\" here. That's \"sutra\".",
		5: "To separate (something) into (some parts)",
		6: "To control (something). Here, with \"se\", it means \"To be controlled by (comeone).",
		7: "\"ku'o\" is how we say when a noun is over. Here, the 3 piles are separate from the \"da\" (which here represents the player doing the separating). Without this ku'o, the sentence reads as though the 3 piles are somehow controlling the permanent.",
		8: "Literally just a pile. That's just the term mtg uses for these. Not group, not set, not partition, just pile. The spanish word is \"montón,\" fun fact.",
		9: "To choose (something).",
		10: "To be random. Here, it modifies the previous verb, so you can read this as saying \"choose in a way that is random.\"",
		11: "\"li'aspo\" = cliva (to leave) + daspo (to destroy) = abandon, kinda. You leave it consigning it to be destroyed. I'm not super happy with it. Notably, the subject of \"daspo\" is supposed to be an event, but here it has to be a player. And yet, here I go again, making up words.",
		12: "\"cukna\" still means \"to choose something\" but here, because of the \"se\" it means \"to be chosen\" because we swap the subject and object.",
		13: "\"pa\" = 1, \"moi\" converts it to an ordinal, here meaning \"first.\" Fun fact, if you combine \"ro\" (each/all) and moi, you get \"all-th\" which means last. It's the one after all of them, so it's last, yeah?",
		14: "Innate capability. Birds <i>can</i> fly. I'm not necessarily saying they <i>are</i> but they can.",
		15: "To be empty.",
	},
	"The Ur-Dragon": {
		1: "\"liryrai\" = clira (early) + traji (superlative) = earliest.",
		2: "drakono is a loan word, believe it or not.",
		3: "\"ceirka'i\" = cevni (god) + krati (representative) = proxy for a god = avatar.",
		4: "\"misybalvli\" = misno (famous) + banli (grand) + vlipa (powerful) = powerful in a way that somehow relates to one's great renown = eminence, I guess. Close enough.",
		5: "To be inside of something. Notably, in english, you can't be <i>in</i> the battlefield, you have to be <i>on</i> the battlefield, but we can avoid that here.",
		6: "\"minde\" means to command something. \"stuzi\" just means place.",
		7: "This \"a\" is an \"or\" in the specific sense that the entire nown is made of either (the command zone) or (the battlefield), and possibly both, because it's not an exclusive or. (That would be \"o nai\" instead)",
		8: "\"nundamba\" = nu (event) + damba (fight) = battle. \"stuzi\" just means place.",
		9: "Cost. Notably, here, it doesn't say \"mana cost\" because this guy reduces the total cost, not just the mana cost. You're gonna have a hard time finding a 0 mana dragon, though.",
		10: "\"mafru'e\" = makfa (magic) + pruce (process) = spell.",
		11: "\"mafpli\" = makfa (magic) + plino (use) = use magic = cast. In this case, we're modifying it with \"se\" so the object is who this spell was \"cast by\" instead.",
		12: "This language doesn't have a word for \"other\" so we're using this word which means \"isn't the same thing as\" instead.",
		13: "To remove (an amount) from (a thing being taken away from). In this case, there's no agent causing this to happen, so we don't care about the subject of this verb. We use \"te\" to turn the verb into \"to have (an amount) removed from you by (the agent that was doing it in the original verb).\" We don't have to specify who that guy is, but they seem like a real piece of work.",
		14: "To fly. There's no better way I know of to write keywords that both saves space and is grammatically correct, but then again, just writing \"flying\" with no qualifier doesn't make much sense in english, either.",
		15: "At least.",
		16: "To control (something). Here, we're using it with \"se\" to swap the subject and object, making the verb \"to be controlled by (something)\" instead.",
		17: "Here we have to be clear that the noun which is being assigned to ko'a is (the dragons which are controlled by you) and not the (you) which is right at the end.",
		18: "You'd think there would just be a variable quantity in this language, right? You'd think you could just say \"X cards, where X is the number of dragons which attacked\" but no.",
		19: "To be a quantity of (something).",
		20: "\"xance\" means hand. The word stuzi here really isn't very necessary. I just have it here because I like the idea of all the zones being called zones.",
	},
	"Aquatic Alchemist": {
		1: "To be water. A better english translation for this word would be \"aqueous.\"",
		2: "\"gafxumpra\" = galfi (change) + xukmi (chemical / drug) + cupra (produce / create) = (change drug) create = to create potions.",
		3: "\"selratkai\" = se ratni (element) + ckaji (to be characterized by something) = element-y thing = elemental. \"ratni\", by itself, means \"to be an atom of (some element) so the \"se\" gets us the element part that we care about. Unfortunately, that means that this translation comes with the implication that the elemental is made out of an actual chemical element, and not water, like it is in this case. Oh well, that's true in english too.",
		4: "\"pa\" = 1, \"moi\" converts it to an ordinal, so this means one-th, which we usually call first in english.",
		5: "\"ja\" means \"or\" in the sense that either of two verbs is true. This is <i>not</i> an easy sense of \"or\" to really get across in english.",
		6: "Really unfortunately, I've already used \"cpacu\" for drawing cards. I think I may change that in the future.",
		7: "\"varboi\" = vacri (air) + bolci (ball) = air bubble. I guess it doesn't have to be air that the cauldron produces, but it's fine.",
		8: "\"galmu'u\" = galtu (high / upward) + muvdu (move) = ascend, rise. This is NOT what the word \"up\" means in the original context. It means that the substance is becoming bubbly. But like, do you want to read \"bubbly becomeance\"? No.",
		9: "Okay, so we don't have a word for an adventure. We <i>do</i> have a word for adventurer. \"capli'u\" = ckape (dangerous) + litru (to travel) = to travel dangerously = to go on an adventure. We can get the actual <i>journey</i>, the adventure itself, with \"selkemcapli'u\". That's option B. Instead, I like \"capli'ulisri\" = adventurer + lisri (story). These adventures come from the storybook plane anyway.",
		10: "To be inside of (something).",
		11: "To put (something) into/onto (somewhere)",
		12: "\"galraipau\" = galtu (high) + traji (superlative) + pagbu (part) = highest part = top.",
		13: "\"ra'i\" comes from \"krasi\" which means \"is a source/origin of (something).\" Here's you're casting the cute little alchemist from the source of exile.",
		14: "",
		15: "",
		16: "",
		17: "",
		18: "",
		19: "",
	},
	"Desolation Twin": {
		1: "nu (event) + to'e (polar opposite of) + se (swap subject and object of next verb) + xabju (to inhabit a place) = to be an event of the opposite of being inhabited = to be uninhabited",
		2: "Not a huge fan of this word, it's tarbi (embryo) + kansa (to accompany) = extra egg(s) = twins. Now... eldrazi don't have eggs (i think) so not the best translation, but this seems to be the canonical way to translate twin.",
		3: "Really nice coincidence: The word eldrazi already follows all the lojban grammar rules for loan words :)",
		4: "skari (color) + claxu (lack) = to lack color / to be colorless.",
		5: "Pronoun similar to we. It means me, and you, and possibly others.",
		6: "To be precise. This <i>should</i> <b><i>technically</i></b> just apply to measurements, and not coordination like I'm using it here, but... I don't think Munda cares.",
		7: "kansa (together) + muvdo (move) = moving together. Coordination!",
		8: "A quantity meaning \"enough\".",
		9: "Blood.",
		10: "To fall/drop. Often gets used with liquids spilling as well.",
		11: "To be possible under (conditions go here). Because of the \"se\", the conditions actually go back there <--- before this next bit.",
		12: "Turn the next noun into a verb. So like \"me do\" is a verb that means \"to be you\". Here, \"me ko'a\" means \"to be them.\" In this context, ko'a refers to the eldrazi.",
		13: "The polar opposite of the next verb.",
		14: "To attract or lure. Due to the to'e, this becomes the opposite, which I guess would be repelling or driving something away.",
		15: "This word has no grammatical meaning, it only emphasizes the next word.",
		16: "se (swap subject and object) + farlu (to fall) + gasnu (to cause) = to cause something to have fallen = to bring down.",
		17: "However.",
		18: "To need something for some reason.",
		19: "A quantity meaning \"too much.\" Too much just as in like, more than a reasonable amount. One of those indefinite but contextual things.",
		20: "To say something. Because of the \"se\" this instead means to be said by someone.",
		21: "Munda gets a closer name in lojban than in Greek. Good for them.",
		22: "Incidentally also known as",
		23: "spaji (surprise) + gunta (attack) = ambush.",
		24: "Chief / leader.",
	}
}