const storyInfo = {
  "MKM-1": {
    1: "\"ni'o\" just means \"we're talking about something new now.\" it's not really necessary for speech, but lojban doesn't <i>technically</i> allow you to imply new paragraphs with an indent like we do in english.",
    2: "\"le\" is somewhat analagous to english \"this,\" so like in this case, I'm not just talking about <i>a</i> sky, I mean the relevant one. The one up there.",
    3: "\"noi\" means \"for which (the thing after 'noi') is incidentally true\" so this means, \"which happened to be-over-Karlov-Manor\"",
    4: "\"la\" indicates that this is a proper noun, unlike \"le\", which is like \"this.\" Another perfectly acceptable way to translate this would be \"la .karlov.manor.\" but that imples that Manor is just the <i>name</i> of the thing, it's not a manor of whatever a Karlov is.",
    5: "Weirdly, \"tsani\" just means it is an <i>expanse</i> of sky, not the whole sphere around the planet. The definitions here are very specific.",
    6: "This little \"ki\" right here is what causes the rest of the text to be in past tense. Because it's right after the word \"pu,\" meaning \"past tense,\" it causes that tense to be the default until something says otherwise.",
    7: "Past tense",
    8: "\"cu\" means (approximately) \"I'm done telling you the subject of this part of the sentence now, and next is the actual verb\"",
    9: "\"dansu\" is one of few examples of a verb that sounds like what it means. Those do not happen often.",
    10: "The sky is not actually really physically dancing. This is an indicator for that. There's a lot of tone indicators in this language, which may not be surprising.",
    11: "\"and\" here in the same sense as you might say \"the boy jumped and ran\" to allow you to combine two predicates that share a single subject",
    12: "I'm not happy with having to split the sentence up like this. The second best thing you can do is say \"it danced such that the property of it containing colors... is true\" which just sounds way worse.",
    13: "This is like if we had a number that meant \"lots.\" I guess we do, and it's called \"lots\" or \"many\" but it is explicitly treated as a number in this language.",
    14: "This is color as in the physical thing, and not the idea of a color, which is its own separate word.",
    15: "There's not a lot of words that are as evocative as I'd like.",
    16: "\"ri'a\" means \"is physically caused by\" and it's just one of a very long list of ways-things-can-make-things-happen. I suppose in this context it's less physically-caused-by and more supernaturally-caused-by, but sadly, that's not on the list.",
    17: "Perhaps the most common word in the language, \"lo\" means \"turn this verb into a noun\" which weird as hell. Like, imagine if you could just take a word like \"run\" and turn it into \"a runner\" and that was possible for any concept the language could express. It works in reverse, too, you can take \"a cat\" and turn it into \"cat (verb)\" (that word is \"mlatu\")",
    18: "Let me tell you, after spending as much time as I have thinking about ways to say different magic concepts in this shit language, we are spoiled for choice when it comes to english. Witchcraft, enchantment, artifice, spellweaving, alchemy, we've got plenty of words. All of their equivalents in lojban are gonna have a \"makfa\" in there.",
    19: "Cascade is such a weird word. What is a \"cascade\"? Can you think of a single, platonic ideal of what a \"cascade\" would be? Not a cascade of anything in particular, just in general. It's like a wave, right?",
    20: "So, again, this language doesn't technically let you use <i>anything</i> to convey meaning outside of its alphabet. Instead you just start a new sentence with \".i\" because \".\" by itself is pronounced as just a glottal stop, so they had to put another sound there to make it audible. The \"je\" modifier means \"and\" so this new sentence is indicated to be continuing the same train of thought as the previous one. The \"je\" isn't required, and neither is the \".i\" honestly. It just makes things consistent :)",
    21: "\"lai\" is like \"la\" but plural.",
    22: "Lojban \"j\" always sounds like an english \"zh\" (despite not being a very english spelling of the phoneme)",
    23: "\"erve\" is one of very few lojban verbs to have 4 letters, because it's a loan word based on english \"serve\"",
    24: "\"ro\" means \"each\"",
    25: "This is a compound word made out of 4 different verbs smushed together. Fully spelled out, this is \"fagri cupra minji dinju\" which can be shortened into that single word. In english, that's \"fire-making-machine-building\" which is kinda close to what a \"pyrowork\" is in-universe.",
    26: "Inside",
    27: "The Tenth District is a proper noun made out of words lojban actually has words for.",
    28: "\"panomoi\" is pa-no-moi meaning one-zero-place (pamoi means first) so the whole thing comes out to mean tenth.",
    29: "\"ge'u\" (pronounced ge-hu) is used to say when \"noi\"'s are over. It's usually unnecessary, like be'o.",
    30: "Create. This word is a combination of the words for \"stuff\" and \"cause,\" which you can kinda see how that makes create.",
    31: "\"Show,\" as in something that is displayed for an audience.",
    32: "\"xaksu\" means \"deplete\" or \"waste\" and \"kargu\" means \"expensive\" so \"xakykargu\", which is a combination of both words, means \"waste expense\" which is about as close as I can get to... profligate.",
    33: "Sadly, lojban doesn't like two of the same consonant in a row, so Izzet is either .izet. or .izyzet. (pronounced ih-zuh-zet) which is worse.",
    34: "\"ka\" means \"state of\" so \"lo ka vlipa\" is saying \"the noun (the state of (to be powerful))\" which usually we just call power.",
    35: "\"e\" joins two nouns together with an \"and\" (like, the logical \"and\" so it is both at once)",
    36: "Same deal as before, but this time it's a compound verb, spelled out fully to indicate it's not a singular concept. \"banli\" means \"great / grand\" and \"ricfu\" means \"wealthy\"",
    37: "District. Another way to write district is \"tutpaupau\" meaning \"territory-part-part\" because districts are usually parts of states which are parts of countries",
    38: "\"lu\" starts a quotation and \"li'u\" (lee-hu) finishes it.",
    39: "\"xu\" is a tense marker that says this is a true-or-false question.",
    40: "\"do\" is a pronoun that means you.",
    41: "This is a compound word made of \"viska\" (to visually see) and \"jimpe\" (to comprehend). I thought it was reasonable to write it this way, instead of \"literally just viska\" because they're not asking if you just see their wealth, it's if you truly grasp their wealth.",
    42: "\"cusko\" is a verb that means \"to say\" but it specifically means \"the first noun says the second noun\" so we have to switch the order with \"se\". If we didn't, it would be like saying that those words somehow spoke an entire manor into being.",
    43: "\"ko'a\" (ko-ha) is a third-person pronoun. So you can use it like \"it\" or \"they.\"",
    44: "\"prenu\" is person, so \"lei prenu\" means \"the people.\"",
    45: "This is a compound word made of \"na\" (not) and \"te benji\". \"benji\" means to send something to someone, so the \"someone\" is the second object of the verb. To switch the subject with that second object, we use \"te\" (\"se\" is for swapping the subject with the first object, which is much more common.)",
    46: "\"pa\" means the number one. \"zvacpe\" is a compound word made of \"zvati\" (to attend) and \"cpedu\" (to request).",
    47: "\"ki'u\" (ki-hu) means \"because of\" in the sense that this next thing is a justification.",
    48: "This state (ka) lasts for quite a while, so there's a \"kei\" at the end to say when it's over.",
    49: "\"claxu\" means \"to lack,\" so this is a state of lacking...",
    50: "\"jdini\" means \"money\" so this state is a lack of money...",
    51: "and finally, \"zabna\" means \"favor / fondness,\" so this state is a lack of money AND favor.",
    52: "all of this gets brought together by the fact that this state is specific to those guys (lei prenu) we were talking about earlier. \"ko'a\" is just one third person pronoun, lojban actually has several. The next one is \"ko'e\", which is exactly the same as \"ko'a\" but used once we've already used that one to avoid conflating the two.",
    53: "This is something called a \"discursive\" that adds additional information to how exactly something happened.",
    54: "Perfect tense",
    55: "\"na\" is similar to \"not\"",
    56: "Fuck I skipped 56",
    57: "This quotation goes for a <i>long</i> time. In lojban, an entire quotation is still considered just one noun, explicitly. Do you think when I say \"I walked the dog. I went to the store.\" that, now, after the quotation, this is still the same sentence? Really, this whole quotation is a noun of a larger sentence which has no verb.",
    58: "Skipped",
    59: "Skipped",
    60: "\"mi'a\" is a pronoun that means me, and others, but not you. It's an exclusively exclusive we.",
    61: "\"tolcau\" is a compound word of \"to'e\" (the polar opposite of) and \"claxu\" (to lack), which we actually saw earlier. lojban has a lot of different types of negation.",
    62: "Skipped",
    63: "\"plikra\" is a compound word of \"pilno\" (to use) and \"krasi\" (origin) so it's like saying \"thing from which usability comes from\"",
    64: "\"tolspofu\" is a compound word of \"to'e\" (the polar opposite of) and \"spofu\" (broken) so it's like saying \"in working order\"",
    65: "\"ki'u\" means \"because of\" (in terms of justification) so adding a \"se\" to the front swaps around the placement of the cause and the effect, making \"seki'u\" mean \"which causes\"",
    66: "\"kakne\" means \"to be able to\" and is most similar to english \"can.\"",
    67: "\"zu'o\" means \"the activity of\" and it can be thought of as being similar to how, this whole time, I've just been sticking a \"to\" at the front of words to make them infinitive.",
    68: "This whole thing is technically one great big verb that means \"to spend [it/them] for these frivolous things,\" but like, as just a verb. You could put this whole thing in a different sentence and just swap the verb out for this.",
    69: "Technically, the next third-person-pronoun we haven't used yet is \"ko'i\" (then ko'o, and ko'u), but I think it's been enough time that we're obviously not talking about either of the previous things referred to by ko'a or ko'e.",
    70: "\"mu'i\" means \"because of\" (in terms of human motivation) so like, these guys are spending money in the very human pursuit of Party Time",
    71: "\"tolvaixajmi\" = \"to'e\" (polar opposite of) + \"vajni\" (important) + \"xajmi\" (funny) = (not important) + funny = unnecessary + funny = frivolous.<br>The words are grouped to the left like that by default.",
    72: "\"c\" in lojban makes a \"sh\" sound, so we have to use \"k\" instead.",
    73: "Present tense. We're actually still in past-tense-is-default mode from the very first sentence.",
    74: "Safe.",
    75: "We, but inclusive this time. I think it would make sense that the Orzhov would explicitly exclude you from the party, but <i>would</i> include you in the rhetoric.",
    76: "To be free to do...",
    77: "Worry.",
    78: "\"stogau\" is a compound word made of \"stodi\" (constant) and \"gasnu\" (cause) so this means \"to cause something to not change\"",
    79: "\"mu'i\" means \"because of\" (in terms of human motivation) so like, we're conserving because of the wartime being all spooky and scary.",
    80: "\"jamtei\" is literally just \"jamna\" (war) + \"temci\" (time)",
    81: "\"and\" in the sense that both of these statements are true.",
    82: "\"jdima\" means cost.",
    83: "Skipped",
    84: "This really means, like \"measured\" or \"quantified\" but the idea is there.",
    85: "This is the separator for the two things joined by that \"ge\" from earlier.",
    86: "Explosion.",
    87: "Skipped",
    88: "\"or\" in the logical sense. There's one possible way to interpret this sentence where it says \"At least one of (the bursts) or (the illusions) reminded them...\" which sounds weird but is a possible interpretation.",
    89: "\"xrula\" is a bloom. \"jifselvi'a\" is \"jitfa\" (falsehood) + \"se\" (switch subject with object) + \"viska\" (to see) = false + (thing that is seen) = false image = illusion. \"se\" always affects the thing to the right of it.",
    90: "To fall.",
    91: "\"fi\" means the next thing fills the (usually optional) second object of the verb. In this case, the stuff is falling from the sky. \"farlu\"'s first object is the destination of the falling, not the place from which you fall.",
    92: "This is a compound word of \"morji\" (remember) and \"gasnu\" (cause) so this means \"to cause to remember\"",
    93: "To live, in the sense of dwelling.",
    94: "Shadow.",
    95: "There's not a good word for Syndicate that doesn't stick the word for \"crime\" right in the name. However, I've made peace with this grave consequence of translation. \"grirmafa\" is \"grizu\" (group / team) + \"mafa\" (literally just the english word for mafia)",
    96: "A \"du'u\" is a fact. a \"ka\" is a state, which is similar, but is more about the existence than the truth of the statement.",
    97: "\"ma\" is like who / what / when / where / why / how, all rolled up into one. It is a pronoun for filling in whatever part of the sentence it takes the place of.",
    98: "\"nurxru\" is \"snura\" (safe) + \"xruti\" (return) so this is \"to return to safety\"",
    99: "Plural \"you.\" It includes you, and others, but not me.",

    "i": "Start a new sentence.",
    "po": "\"po\" means \"which is specific to [the thing after 'po']\" which usually just means it marks a possessive.",
    "be": "\"be\" allows you to modify a verb by adding the object of the verb without the usual grammatical semantics. For example, you do something like this when you say \"You can do it.\" \"Can\" is a verb. Really, the only thing \"You\" are doing in that sentence is can-ing, but that's vague, so the extra \"do it\" at the end specifies exactly what you... can.",
    "beho": "\"be'o\" tells you that the \"be\" that began earlier is over now. Usually you don't need it, but when sentences get complicated it helps make sure we're on the same page.",
    "noi": "\"noi\" is kinda like the \"which\" in the sentence \"Take that one which is red.\" The one to take may have already been indicated by the \"that,\" but the \"noi\" provides some additional information.",
    "kuho": "\"ku'o\" tells you that the \"noi\" from earlier is over now. Usually you don't need it, but it's useful to make things clear."
  },
  "Oracle of the Alpha": {
    1: "\"bavyxusta'a\" is \"balvi\" (future) + \"xusra\" (claim) + \"tavla\" (speak) = predict speak = tell the future. Because of the \"lo\", this is a noun that does that, in this case telling the future.<br>Notably, this is not \"a person whose job it is to tell the future,\" that's a different construction.",
    2: "While you <i>can</i> say \"alpha\" in lojban, there's no specific word for it, so you're either gonna be saying \"the letter a in greek\" or \"the first letter of the greek alphabet,\" neither of which are very close to the goal. I considered saying \"first set,\" but that just makes it sound like this guy's a piece of cardboard. Way less cool.",
    3: "\"danlu\" really means \"animal\" or \"thing that is animate,\" both which are close, but sound kinda disconnected from this guy, who is clearly a sentient, living dude with like, understanding of the nature of the universe. However, to be fair, \"creature\" sure doesn't sound great either, if you think about it.",
    4: "Bird",
    5: "\"makfa\" (magic) + \"certu\" (expert) = wizard",
    6: "Keywords are a weird thing. They're there partially to save space, but they don't <i>work</i> grammatically. They imply so much <i>around</i> the keyword, which doesn't translate nicely into something like this. This guy <i>is</i> flying, but writing that sentence fully kinda gets in the way of saving space. So, let's just defer to the way every natural language does it, and just write the verb.",
    7: "Magic is a game that really really needs to use the same words to indicate when things operate in the same ways. Triggered abilities always always use the words when, whenever, or at. So I figured, why not just use one word for all triggered abilities? All triggered abilities start with this word, that means \"after (the first noun), (the second noun) happens.\" It's made of mulno (to be complete) + cabna (is currently happening) so mulcabna by itself means (the first noun) is after (the second noun). The \"se\" swaps the two nouns.",
    8: "\"nerkla\" = nenri (inside) + klama (go to) = enter.",
    9: "\"nundamba\" = nu (event) + damba (fight) = event of fighting = battle. \"stuzi\" is just a position that doesn't change. Like a zone in a game, for example.",
    10: "\"mafyzba\" = makfa (magic) + zbasu (create) = conjure. It's uh... definitely not as evocative of conjuring, but it's pretty close. I'd be able to do it better if I knew how they wrote conjure in other languages.",
    11: "The Power Nine, which, here, is literally \"The set of things that are called 9 of powerful\"",
    12: "The (proper noun) set of things that are called...",
    13: "\"so\" is 9, and \"soz\" is 9 in verb form.",
    14: "Power.",
    15: "\"ne'i\" is like \"in.\"",
    16: "\"ckusro\" = cukta (book) + sorcu (storage place) = library. \"stuzi\" is just a position that doesn't change. Like a zone in a game, for example.",
    17: "\"and\" in the sense of \"I do this and then that.\" The \"gi'e\" connects the two predicates, and the \"babo\" implies that the first one happens before the other.",
    18: "\"kasygau\" = kalsa (chaotic) + gasnu (cause) = mix together disorderly, i.e. shuffle.",
    19: "\"gunta\" means to attack.",
    20: "\"prujungau\" = purci (past) + djuno (fact) + gasnu (cause) = to cause (current facts which were known in the past) = to have seen the future = scry",
    21: "The number 1.",

    "po": "\"po\" means \"specific to,\" which usually just means it marks a possessive.",
    "ro": "\"ro\" means \"each.\"",
    "nu": "\"nu\" means \"the event where this next thing happens.\"",
    "ti": "\"ti\" is a pronoun that means \"this.\" I am making an executive decision here, the cards just say \"this\" instead of \"let me spell out my whole name real quick\" because I don't like that. It can be ambiguous in english (if you're not well-versed in how mtg works) but this is lojban, it should be much more clear.",
    "do": "\"do\" is a pronoun that means \"you.\" Isn't it weird that magic cards just call you \"you?\" Not \"this thing's controller\" or something? I like it, of course, but it's one of those things this project makes you confront and consider.",
    "cu": "\"cu\" means \"the subject of the sentence is over now. here comes the verb.\" which is usually not necessary.",
    "kei": "\"kei\" means \"that event that began earlier is over now.\"",
    "poi": "\"poi\" means \"which are\"",
    "vitno": "\"vi'ordai\" = vitno (stay, unmoving) + dacti (thing) = thing that continues to exist = permanent, in mtg terms."
  }
}