const storyInfo = {
	"general": {},
	"Comfey": {
		1: "Greek doesn't have a word for \"lei\" in particular (but neither does English). So instead we're gonna use \"Γιρλαντα\" (garland). For the \"comfy\" part, Greek has \"άνετος\". We squish 'em together, you get Γιρλάνετο(ς). (That 's' at the end only shows up sometimes.) <b>Look at how fucking good I am at assembling foreign puns.</b><br><br>The only part of the name I couldn't fit in cleanly is the 'fey' part, because it's fairy-type. We're... not gonna be able to fit that in, sadly.",
		2: "This word is where \"synapse\" came from (broadly). It's created from \"syn-\" (together, like in synthesis) and \"hapto\", which means touch. That's where haptics come from. Here it's a verb that means to join things together, so they together-touch.",
		3: "Say this word with your mouth. Say Loo-LOO-dia. Anyway, this word's etymology is unknown. It looks somewhat similar to some words for \"lily\" (a similarity that remains to this day) but I can't find anything beyond that, even if I search beyond wiktionary.",
		4: "!To the.",
		5: "This word is so similar in meaning to the English \"exceptional\" that you might assume they stole it from French, because they did. Greek seems to be lacking in words that mean \"very\". You've got πολύ, that's the main one.",
		6: "This word has nothing to do with \"therapeutic\", though that word is Greek in origin (and will appear in other places in this translation). This word comes from the word for causing something to grow, \"τρέφω\" (in the sense of rearing children or tending flowers, and similar). Stick an adjectivifier on the end and you have an adjective for \"something that promotes growth\" which is what something nutritional does.",
		7: "Not to distract from the translation, but if Comfey is just a fairy that likes flowers (thereby not being a grass type) why is the vine so good for you? Surely this small animal that brightly colors itself would be poisonous.<br>Anyway, I'm translating this as \"κλήμα\" instead of \"άμπελος\" because άμπελος is apparently very very associated with grapes, which Comfey is not. Fun fact: Ἂμπελος was the name of one of Dionysus's lovers, and he died after he mocked the moon god. Rookie mistake.",
		8: "!Possessive its.",
		9: "!This.",
    10: "ανα- (like English \"re-\") + -ζωο- (life) + γονεί (no clue where that came from, but that's the giving part I guess)",
		11: "!Plural neuter the.",
		12: "!And.",
		13: "!Plural neuter they.",
		14: "I'm unsure if this is the best word to use. It can mean \"to produce\" but it can also mean \"to take something off\" (ie clothes) or \"to take something out\".",
		15: "Feminine a. This word is not strictly necessary, and would get omitted by a lot of speakers, but this is Pokémon, and at some level, I think we're writing for children here. We include the article.",
		16: "I love it when these words end up being Greek in origin. Aromatic means aromatic, yes.",
		17: "If you're wondering why this word isn't \"άρωμα\" (which is also a word) it's because \"άρωμα\" refers to the <i>thing</i> that is aromatic, the thing that produces the smell. Which makes sense, something aromatic is similar to a smelly thing, which should be what the \"aroma\" part refers to.<br>Anyway. This is the word for the scent itself. No etymology facts.",
		18: "I think it would be wrong to say \"μπάνιο\" (banio, bath (that's where Spanish got it btw)) here because μπάνιο seems to just refer to the bathtub itself. I'm sure you could still say μπάνιο and people would get it. I don't know.",
		19: "This is like the \"which\" that we use when we're talking about items for which some kind of property is true.",
    20: "Participle of \"παρασκευάζω\", which means \"to prepare\". \"παρα-\" (para, like the English para-) + \"σκευάζω\" (skevazo, to arrange)",
		21: "!With.",
		22: "!From.",
		23: "!Singular neuter the.",
		24: "I wish I could keep the alliteration here, but the rest of the page uses this word to describe picking flowers, and I can't find a similarly good word that starts with a B.",
		25: "!To have.",
		26: "Singular neuter a. This word is not strictly necessary, and would get omitted by a lot of speakers, but this is Pokémon, and at some level, I think we're writing for children here. We include the article.",
		27: "Relaxing. It comes from the word \"χαλαρώνω\" (chalarono) which is a verb that means to cause something to relax.",
		28: "από- (from) + τέλος (end) + some inscrutable PIE at the end. It means effect, or result.",
		29: "So / Therefore / Thus. Most similar to thus, but it doesn't seem to carry the archaic connotations that the English \"thus\" has.",
    30: "Here, \"this\" is being used as a determiner, not a pronoun. Weirdly, in Greek, you gotta add an article after the determiner to basically end up saying \"this, the Pokemon\".",
		31: "I waffled back and forth a lot about whether this should remain in the Latin alphabet or not, but here's the thing, I don't care, having a random bit of non-Greek in here looks dumb.",
		32: "!To be.",
		33: "Demo- (people) + philes (love). Loved by people. Popular. Easy peasy.",
		34: "!Like the word \"to\" but it could also mean in, on, at, it's a very general-purpose conjunction.",
		35: "!Many.",
		36: "The word for people is just \"anthropo\".",
		37: "Guess who didn't know what a posy was until now. I thought a posy was a kind of flower, but NO, posies are just a name for groups of flowers. Anyway, this seems to be the best Greek word to describe a similar bunch of flowers. You may notice that it looks a heck of a lot like the word bouquet. Blame the French.",
		38: "To collect, or harvest. Here, we're using it in the context of picking flowers, which I guess is harvesting.",
		39: "To stretch. This comes from the same root word as \"tentative\", which, weirdly, was imported from Latin. That doesn't happen often.",
    40: "Sticky. I believe this comes from the word \"κολλάω\", a verb that means to glue or stick something. You'll see that one later.",
		41: "!Exo means out. Like an exoskeleton.",
		42: "!Head.",
		43: "Similar to the word \"to\" in \"I want to buy this.\" It lets you treat a verb like a noun, and create ~various subjunctive moods~.",
		44: "!For, in a lot of senses.",
		45: "!To adorn, decorate, or otherwise bedazzle.",
		46: "This is an adjective that here acts upon the next word. It turns a possessive into a ~reflexive~, like myself, yourself, itself.",
		47: "\"When\", but in the sense that it's a statement of the time that something happens, rather than a question.",
		48: "!Doesn't, not, didn't. Lots of falsifiers.",
		49: "To feel in the sense that you can feel good or bad or sick or etc.",
    50: "Awkward or uncomfortable.",
		51: "To glue, or stick something to something. Fun fact: That \"α\" was at one point removed from the word, and then it showed up again later.",
		52: "Weird thing about Greek: In cases like this, where the direct object is a pronoun, you put the object before the verb. Here, τα means them.",
		53: "Hey, another word you recognize. Soma means body.",
		54: "Surprisingly, this has no (or very, very little) shared history with the word \"irrigate\". I thought they sounded similar.",
		55: "To generate or produce. It comes from παρα- (like the English para-) + -άγο, meaning to lead something somewhere.",
		56: "!Feminine singular the.",
		57: "To be emitted, or to emerge.",
		58: "I didn't know that petal was an originally Greek word.",
		59: "Believe it or not, therapeutic means therapeutic. There's an argument that I should have said pharmaceutical instead, which is another word for healing, but I think I prefer therapeutic in this context. The major difference is that therapy implies someone caring for you, but pharmaceutic implies that it's medicinal. Comfey isn't medicine, Comfey is a friend.",
		61: "I'm unsure if this is a situation appropriate for για. It's a bit hard to research though. I've found a few sources saying this works, but none saying this is how the phrase ought to be translated.",
		62: "An indefinite pronoun/determiner that refers to some thing.",
		63: "Hey look at that, reason is logos. Fair enough.",
		64: "Θα is a particle that, like να, denotes some change in how the next verb should be understood. Θα usually denotes futurity, which is the fun word for this sort of thing.",
		65: "That \"μαρ\" (mar) at the beginning is actually the same exact root that you can find at the beginning of the English word \"murder\". Neat!",
		66: "After, usually used with subjunctives like this.",
		68: "Here, because we're talking about Comfey, but we're not talking <i>to</i>Comfey,we need to stick a \"the\" in front of its name to convey that. This is true for people's names too. The Steve went to the supermarket. The Anna is over there. The Boo is wondering why this is a feature of so many languages.",
		69: "Have you ever thought about how the verb \"smell\" works in both directions? You can smell something (receive the scent), and that something can smell (produce the scent). The same is true in Greek, but it's still weird, right?",
    70: "!Very.",
		71: "Good. That \"ωρα\" at the beginning originally had to do with time, and the word meant \"timely\". Now it just means good in a very broad range of senses.",
		72: "!All of.",
		73: "!To wear.",
		74: "This just means different, and you can still kinda see it in the word.",
		75: "κάθε (every) + ένα (one) = each. Κάθε also means each sometimes, but for countable things like Comfey, I think καθένα is more appropriate.",
		76: "When saying \"among\" or similar, you basically say \"things from this group\" which is why από appears here.",
		77: "A possessive adjective that lets you create things like \"my own\" or \"its own\".",
		78: "Special in the sense of being particular or specific.",
		79: "I hate this fucking mouthful of a word, imagine if every time you wanted to use something you hat to spell onomatopoeia. Anyway it comes from the adjective \"χρήσιμος\" (chrisimos) which means useful, and the last part \"ποιώ\" means to make. It means to make useful of something.",
    80: "To evolve, unfold, or develop in some way. It comes from \"ανα-\" (like English re-) + \"πτύσσω\" which means to fold.",
		81: "\"ίδιος\" (self) + \"-ότητα\" (-ness) = a property of something.",
		82: "To prefer something. Comes from \"προ-\" (pro, towards) + \"τιμή\" (honor, esteem).",
		83: "Area. Comes from \"περι-\" (peri-, around, like in peripheral) + \"έχω\" (verb that means to have)",
		84: "I wanted to put an indefinite determiner here, because the text isn't talking about just one Comfey, it's talking about all Comfey in general. However, the indefinite determiner in Greek can mean either any or none depending on context, and I don't trust myself.",
		85: "This is a bit of a strange word. That \"ευτυχι\" at the beginning is a combination of the \"eu\" (an archaic word that means good) that we still see in euphoria and a word that means \"to act\".",
		86: "To gain or acquire something.",
	},
	"Spheal": {
		"1": "Yeah, there's not much to talk about as far as the \"pun\" goes. I should mention, unlike Comfey, we're gonna call this noun feminine. I would've really liked to have come up with a good excuse to make all the Pokémon neuter gender, but seals are feminine in Greek, and like... the name just looks better <i>without</i> purposefully breaking grammatical expectations.",
		"2": "We're not sure where this word came from. The leading theory is that it came from the same source as \"spread\".",
		"3": "Honestly, this \"foka\" name for seals is way more common in a lot of European languages. This one you can blame Germany for, they're why we use \"seal\" instead. Like with a lot of words, scholars used \"phoca\" to little success to show off how knowledgeable they were. Phoca's got a pretty nice bounce to it though, y'know? It sounds like what you would call the little bouncy walk they do.",
		"4": "Okay is Sealeo a pun on \"seal\" or \"sea\"? It's a sea lion, so \"seal\" is unnecessary, right?I considered using the former, but then you get \"θάλεονταρι\" (thaleodari) or similar, which <i>immediately</i> flies in the face of that grammatical gender stuff from Spheal.",
		"5": "Fun fact: Not the original Greek word for lion! The original word, λεών (leon) which of course needed to be borrowed from the language of people who had lions. We're not sure which one, though! So the word got to Greece, and eventually got a suffix thrown on the end meaning \"small\". So the word for lion went from being \"lion\" to \"little lion\" essentially. We did the same thing a few times, of course, like with monkey, chicken, quail, rabbit, kestrel, etc. To be fair, English itself can only really be blamed for chicken in that list.",
		"6": "Not a huge fan of this one, but it <i>is</i> a word that combines two existing words to make a name. And what a name! Bow before Vasillipus!",
		"7": "I have <i>no</i> evidence for this, but do you think this word might come from the same place as \"vassal\"? Even though that <i>looks</i> like a B, it's pronounced like a V, so... maybe?",
		"8": "2 things:<ol><li>I completely forgot what a hippocampus was, that would've made this word look a lot less like \"hippo\".</li><li>Has it ever occurred to you that a hippopotamus is literally just a river horse?</li><li>Secret third thing: You may remember \"potamos\" from its starring role in \"Mesopotamia\" which literally just means \"between rivers\".</li></ol>",
		"9": "\"παχύς\" (pachis) means fat, so if you stick an -ουλό on the end, you get a less extreme version. Chubby!",
		"10": "Yeah, it's just sphere again, but check it out, this is where that neat \"-ic\" suffix came from! It's \"music\" because it's of the muses!",
		"11": "There <i>used</i> to be an \"ho-\" at the beginning of this word, so it had \"homo-\" in it, which of course makes the similar-ness aspect more sensible.",
		"12": "Usually this word means \"with\" but not today, I guess. Apparently this word just uses \"with\". Shrug. That is a command.",
		"13": "\"κοντός\" originally referred to a pole, like the weapon that you poke people with. Now I don't know if you're aware, but those are pretty long, so what gives? This gives: \"κοντός\" referred to the shorter <i>kind</i> of pole, as opposed to a δορῠφόρος, which was the longer kind of pole.",
		"14": "\"επί-\" means \"on\", and \"πέδον\" means foot. It flat, its feet are on the ground. The feet of the tail, the feet that the tail has. Those feet.",
		"15": "Man, this word didn't go anywhere. Everyone outside of Greece was like \"yeah we'll make our own word thanks\" on this one.",
		"16": "The word for \"plush\" is \"λουτρ\" (loutr) because otters have soft fur and the French word for an otter is a loutre.",
		"17": "This just means fur, but I want you to hear the (translated) way that wiktionary defines this word:<br>\"the rich and soft fur of some animals\" (it uses a different word for fur)",
		"18": "<span style='color:#87CEEB'>This color</span>. It either comes from the word for turquoise, or those blue eggs, not sure.",
		"19": "This word can mean either \"enough\" or \"several\" depending on context.",
		"20": "!Spots.",
		"21": "I'm sure you can see the \"different\" part of this word, but that \"ών\" at the end makes this turn into a word that modifies the noun.",
		"22": "Yeah, the word for size just has \"mega\" in it.",
		"23": "!Back.",
		"24": "This comes from the same source as the word \"apocalypse\", which you may remember from my other translations has a much less dramatic meaning in Greek. An \"apo-\"calypse is a revelation, an event of something being revealed. So a calypse itself is an event of something being covered. And there's our source! That \"ma\" at the end can still be seen in \"theorem\" and \"grammar\".",
		"25": "Soft. The \"afro\" part comes from the word for sea foam. That's also where Aphrodite's name comes from, because remember that one time she ocean?",
		"26": "Together. Here you can see that \"me\" from earlier in a more common setting.",
		"27": "Layer. This sound can still be seen in \"stratosphere\"",
		"28": "This is the source of the word lipid.",
		"29": "!Down",
		"30": "From. Combined with \"down\" this literally just means from below.",
		"31": "!To retain.",
		"32": "Yeah, the word for heat just has a thermo- before a suffix that makes it a noun.",
		"33": "!To protect.",
		"34": "Yeah, the word for cold is just \"cryo\". It's a bit hard to see, because that \"υ\" is really a y... but it is.",
		"35": "Cyclical, and therefore circular.",
		"36": "I think this word literally means something like \"spongy-teeth\"? The \"δοντες\" part is pretty obvious, but what's \"χαυλιο\"? I got nothing, but wiktionary seems to think it bears some familial resemblance to the word for \"spongy\".",
		"37": "\"pro-\" (towards) + \"-exo-\" (out) + (suffix that makes it a verb). It projects out, it protrudes.",
		"38": "Top, upon, or in this case, upper.",
		"39": "So this word just means jaw, but it's a little unclear where it came from. It's suggested that it came from \"ψίομαι\" (psiomay, that is not a silent p) which is a verb means to chew. That \"m\" disappears when you use it to describe someone else chewing. I imagine that's a lot more common, because you're not chewing if you're talking about how you're chewing.",
		"40": "This comes from the same source as \"strangle\", \"string\", and \"strong\". What a weird bit of Word Lore.",
		"41": "Ears. Hey look, it looks like the word audio.",
		"42": "\"κοντό\" means short, \"χοντρα\" means fat. Stubby!",
		"43": "In Greek, the words for find and wings are identical. Not even identical, it's just one word. BTW, that's the same root as in pterodactyl!",
		"44": "Yeah, it just means lower part. That's our word for underside. Not even squished together, like in English.",
		"45": "The <i>FRENCH</i>, at it again! Importing color words!!!! Bastards",
		"46": "So Greek uses the semicolon as a question mark. You just have to get past that when you read a semicolon. \"It's a question mark;\" I hear you ask. \"But then what if you have a list that needs clausal separators;\"<br>Well, you have a few options: You could always restructure your sentence· you could just use commas, but that has limits· or, you could use the Upper Period (·) that is. LITERALLY half a colon. A semi-colon, if you will.",
		"47": "",
		"48": "",
		"49": "",
		"50": "",
		"51": "",
		"52": "",
		"53": "",
		"54": "",
		"55": "",
		"56": "",
		"57": "",
		"58": "",
		"59": "",
		"60": "",
		"61": "",
		"62": "",
		"63": "",
		"64": "",
		"65": "",
		"66": "",
		"67": "",
		"68": "",
		"69": "",
		"70": "",
		"71": "",
		"72": "",
		"73": "",
		"74": "",
		"75": "",
		"76": "",
		"77": "",
		"78": "",
		"79": "",
		"80": "",
		"81": "",
		"82": "",
		"83": "",
		"84": "",
		"85": "",
		"86": "",
		"87": "",
		"88": "",
		"89": "",
		"90": "",
		"91": "",
		"92": "",
		"93": "",
		"94": "",
		"95": "",
		"96": "",
		"97": "",
		"98": "",
		"99": "",
		"100": "",
		"101": "",
		"102": "",
		"103": "",
		"104": "",
		"105": "",
		"106": "",
		"107": "",
		"108": "",
		"109": "",
	}
}