const storyInfo = {
	"general": {
		
	},
	"Lightning Bolt": {
		1: "Hey, would you say that naming a card like this is the subject or object of a sentence? What, you don't think this counts as a sentence? Wrong. Greek needs to know. It seems like this should be what they call the 'nominative' case, which is the most common one.",
		2: "'Astrapí' here means lightning, or flash.",
		3: "This is actually the same 'bolos' that 'bola' (the weapons that you throw) comes from.",
		4: "This is a very general word, that could mean all sorts of causal things. I suppose you could also use a word for like 'give'? Isn't it weird how we use the word 'deal' in this context? Why do you give people damage?",
		5: "I <i>think</i> damage is supposed to be singular here. I have no idea.",
		6: "Se can mean damn near any kind of 'to' in Greek. In, on, to, at, most conjunctions.",
		7: "Maybe I'm just missing a better word, but 'whatever' certainly fits the bill.",
		8: "Apparently this only means 'target' in archery contexts, but 'target' also doesn't mean target in most contexts in English. This word can mean like 'aim' or 'goal' which is... just like English.",
		9: "Greek just sticks a Δεν in front of anything that ain't.",
		10: "Greek is very conjugated. The 'έχ' part means 'have' and the 'ει' part means 'it is a singular person who is doing the having'. With nouns, the gender matters, and it would probably be more accurate for me to stick a female pronoun like 'αυτή' after this word.",
		11: "Hey, look at that, the word for hearing sounds like 'acoustic'.",
		12: "This is what we in the business call a 'subjunctive'. That's the fun term for clauses-within-sentences like this. This is a pretty simple one, but in English, you see this kind of thing whenever you say \"I wish that <wish goes here.>\" Isn't that weird, that the wish can just be its own whole sentence? \"I wish I were taller.\" In English, we have an entirely new way of conjugating \"be\" to allow those clauses to be less confusing. In Greek, you get to see the \"να\" and figure it out.",
		13: "I want you to try and say this word. The 'ch' sounds like a cat hissing, and the 'τ' just makes a t sound. So say it, go 'chti-pa-ei'!",
		14: "I cannot stress enough that the Greek question mark is a FUCKING semicolon. Why?? As best I can tell, we should blame the Salvonic Church in particular.",
		15: "I <i>believe</i> this attribution here calls for the 'genitive' case, usually used for portraying relationships between things. The quote has a relationship with its speaker, right? Anyway, that means we gotta stick an O in front of Snerd's name. It would be an H if Snerd were a girl, and maybe they are, but O is the default.",
		16: "I want to really draw your attention to the fact that this ends with an 'ντ'. In Modern Greek, the δ only makes a very soft d sound, closer to the 'th' in 'the'. So our good buddy Snerd here, with a hard d at the end of their name, must simply be okay being called Snernt. How sad. Fun fact, in Greek, 'Avocado' is basically spelled 'Abokanto' for the same reason. It uses a beta! But not a delta!",
		17: "I am <i>very</i> not confident about my usage of this word. Is it okay to use this as an adjective? Probably. What about as only a <i>piece</i> of an adjective that's being used as an epithet? I dunno! I assume that the capital letter makes it pretty clear this is a proper noun!",
		18: "This one is even weirder! It's a <i>noun</i>! Like, morphologically! I'm really hoping it's fine to just stick a noun in front of a noun like this. All the examples I can find are things that make a lot more sense as adjectives, like leather or wool, but are also used as nouns.",
		19: "This one I'm pretty confident with. Sure, I accidentally ended up using the ancient greek version of the word for half of this project, but I figured it out.",
		20: "I'm really unsure whether this language is OK with you just saying it deals 3 of 'a concept' to something. Gonna play it safe."
	},
	"Teferi's Tutelage": {
		1: "Oh hey look, the word for education has \"peda\" in it like \"pedagogy.\" Neat. Unfortunate that we can't preserve the alliteration, but oh well.",
		2: "Possessives in Greek always gotta go after the noun they're modifying, sadly.",
		3: "A lot of Greek names, I've noticed, put the stress (marked by the accent) on a syllable that English speakers would find strange. Anna and Adam are both voiced with the stress on the second 'a', and in Daniel, the 'i' receives the stress. So we're just gonna get as close as we can to English here.",
		4: "\"Γοητεία\" could also mean things like \"beauty\" or \"attractiveness\" but then again, so could \"enchantment,\" so I guess it's fine. The relationship with magic isn't just superficial, the \"γοη\" at the beginning comes from the ancient Greek \"γόης\" meaning \"sorcerer\" or \"wizard.\"",
		5: "Greek has 2 \"when\"s. \"Πότε\" is for asking questions, but here, \"όταν\" is for making statements. I like that there's a distinction. It's kinda weird that you can answer \"when are we going?\" with \"when the train comes.\" You can't do that with \"what\" or \"how\" outside of rhetorically breaking normal conversation conventions.",
		6: "Dude, Greek really loves putting articles everywhere. In some contexts you have to put a \"the\" in front of the name of the person you're talking about. You can't just say their name. Or at least, it's not \"correct\" to. But only sometimes.",
		7: "I really like that they're getting rid of the \"the battlefield\" part of this text :). Makes my job a lot easier. Anyway, \"μπαίνει\" means to enter, and would usually be followed by the name of the place being entered.",
		8: "To pull, tug, or pluck. That's also one of the meanings of \"draw\" but certainly not the most common. Honestly, that's kinda our fault. Pull makes much more sense in the context of grabbing a card from your deck.",
		9: "This is like English \"a\" but female. Cards are female, didn't you hear? Word Scientists figured out the gender of every single card in existence.",
		10: "Believe it or not, karta means card.",
		11: "Greek uses \"and\" in many of the <b><i>exact</i></b> same ways English does. Even in some of the weirder contexts! Very surprising to me.",
		12: "\"μετά\" has <i>nothing</i> to do with the concept of self-referentiality like in English. Big surprise, to me. It also seems to have nothing to do with the Latin \"meta\" as in measurement. Its etymology seems very uncertain! The modern usage of the word can mean many things, like \"after\" and \"therefore\" and \"with\". The \"with\" likely comes from its similarities to \"με\" which also means \"with\".",
		13: "To reject or refuse. Also sometimes used to mean throwing something away. This one's a win for English, we have a way better word for getting rid of cards. You dis the cards. It's right there in the word.",
		14: "Now you may be saying \"hey, I thought 'πότε' was only used for questions\" but this is \"Όποτε\" which is very different. It's a conjunction that means whenever. I can honestly say I never thought about the part of speech of 'whenever' until today.",
		15: "The ς at the end indicates that it's you doing this.",
		16: "I don't feel like this is worth an article, Greek. Fine. Neuter singular definite article I guess.",
		17: "Here \"target\" is used as an adjective, kinda...? It's like, a modifier. You target the opponent. They are targeted. Here, I opted out of adding the usual \"-ικός\" that an adjective would have. It's not an opponent that is target-al. I'm pretty sure this is still grammatically correct. Also, normally this would have an ς at the end, but here, the opponent is neuter.",
		18: "Your opponents are your anti-pals, isn't that cute. The etymology has, I'm pretty sure, no connection between the two, obviously.",
		19: "From what I was able to gather looking at other, actual Greek game rulebooks, one word that's used for this kind of thing is \"Ρίχνει\" which means to drop. I think that's a valid word to use. But here, in MTG, we have this whole thing going where putting cards into your graveyard is called milling because one card in 1993 was named millstone. Every other language uses a similarly grind-y word for milling, and Greek should as well, I think.",
		20: "Yeah the Greek two is pronounced dio. Not duo.",
		21: "To put. Fun etymology fact: That \"Βά\" is (probably) the same \"ba\" that eventually made its way into the English word \"ban.\"",
		22: "Feminine plural accusative definite article moment",
		24: "Greek possessives are weird. I guess this isn't a possessive per se, but it sure gets translated like one.",
		25: "If you also started wondering why English seems to be the only European language to call libraries by a name that doesn't obviously include a root that looks like Bible, blame the French. The English \"library\" is based on the (old) French \"librairie\" meaning bookstore.",
		26: "In Greek, this word is both the masculine and neuter way to write possessives. I have opinions about this.",
		27: "This is a contraction of \"σε\" and \"το.\" \"το\" just means \"the,\" but \"σε\" has a much more interesting usage. It's most propositions. It can mean to, at, on, in, by, whatever. It's not every preposition, but it's a lot of them.",
		28: "Neuter singular accusative definite article moment",
		29: "\"νεκρο-\" (dead) + \"τάφ(ος)\" (grave) + \"-είο\" (building). Fun fact, that \"τάφ\" is where we get \"epitaph\" from.",
		30: "Masculine singular nominative definite article moment. Laws are all masculine, didn't you hear? The Word Scientists figured it out.",
		31: "Greek doesn't really have the \"h\" sound anymore, so even though this is obviously based on \"hexa\" there's no h.",
		32: "This is the same \"nom\" that eventually became the English \"number.\"",
		33: "Most abstract concepts in Greek are feminine. Not this one. At least not by <i>default</i>, it seems.",
		34: "The word for time + a suffix to make it an adjective.",
		35: "\"ανα\" (≈backwards) + \"δρομ\" (running) + \"ικός\" (adjectivify) = running backwards-ness. This is the part I'm the least sure about.",
		36: "In Greek, this word is both the masculine and neuter way to write possessives. I couldn't find a good source for Tarassel's gender.",
		37: "This is just their name. No surprises.",
		38: "To be. You may now get me started.",
		39: "That \"εύ-\" at the beginning is the same \"eu\" in euphoria. It means good. The \"κολος\" I can't help you with. Somehow, it causes this to mean easy.",
		40: "This is like the \"to\" that we stick at the beginning of subjunctives.",
		41: "To comprehend. There seems to be another word, \"κατανοεί\" that seems to describe some kind of deeper understanding. I'm making a judgment call and saying that while Teferi has a deep understanding of time, he doesn't think much of it, and would totally be a little flippant about how he refers to its laws.",
		42: "To be sufficient. It seems like this is the common phrasing for \"as long as\" in Greek, as far as I can tell.",
		44: "This is the same place that we get the \"heur\" in heuristic from",
		45: "I <i>think</i> this should be masculine, because laws are masculine. However, seven isn't even a noun, in this case. That being said, I'm pretty confident that laws are still masculine if they're invisible.",
		46: "Hey look, the word for first has proto in it. Neat.",
		47: "They dropped the H at the beginning of \"hepta.\" There used to be one there, or at least, a symbol that indicated you were supposed to breathe more at the \"e\" sound."
	},
	"Conflux": {
		1: "This word can mean \"the flow of energy\" and it seems like the best you're gonna get in Greek. It could also mean just a gathering of people, but like, a conflux in English could also mean that. Confluence would be a more common word, though.",
		2: "Bro I ran out of good magic words so fast. English really has the right idea, stealing words from every language that sounds cool. Anyway, this word means ritual in like, religious-ish contexts. Which again, that's how we use ritual too. I think I'm doing fine.",
		3: "This word is weird. There's two competing spellings of the same verb, each with completely different conjugations, and it seems like one of them is somehow more \"formal\" than the other. I guess it's kinda like how we have sneaked and snuck? Drunk and drank?",
		4: "I find this general-purpose preposition really funny. It could mean damn near anything. At, on, to, for, on in the temporal sense. We do the same thing sometimes but that doesn't stop half of all Greek sentences from sounding like \"I walk at you\"",
		5: "Library. Not going on the bookstore rant again.",
		6: "You, but like in an object of a sentence. Isn't it weird that \"I am me\" requires two different pronouns, but \"You are you\" doesn't? Other pronoun don't do that.",
		7: "Feminine \"a\".",
		8: "Greek has 2 competing words for white. The other word, \"άσπρος\" is an import from Latin, but this one here is 100% Greek. This is where the first part of \"leukemia\" comes from.",
		9: "All cards are feminine, except in Portugal, Brazil, Israel, Romania, Ireland, and a few other places. In Scandinavia they're non-binary.",
		10: "Make a \"bleh\" sound with your mouth. This word is a direct import from French \"bleu\". That's like, a dark blue, whereas \"γαλάζιο\" is a light blue. Not to be confused with cyan.",
		11: "This word comes from the Moors, a North African people.",
		12: "We're pretty sure this word came from the word \"κόκκος\" meaning seed, or grain. Why? Why did it do that? Can't say.",
		13: "And.",
		14: "Based on the word \"πράσον\" meaning leek. This means leek-green. Now you might be thinking, \"hey, what about cholorophyll? where'd that come from?\" and the answer is Greek. Greek used to have \"χλωρός\" (chloros) meaning verdant/blooming. It doesn't anymore. The leeks won the battle, and the chloros has fallen out of use.",
		15: "Dude. The Greek word for reveal. Is Apocalypto. Here's how that happened: First, the Greek word is just \"απο-\" (un) + \"καλύπτω\" (cover). \"ἀποκάλυψις\" (apocalypsis) is a noun forming the event of uncovering, which came to mean a revelation. And the word reveal is right there in revelation baby!!!! But yeah it's a much less dramatic verb in Greek. The same way that reveal, despite coming directly from revelation... is not very dramatic.",
		16: "In Greek you gotta add an article after this/that/these/those. You just gotta.",
		17: "Put.",
		18: "Feminine \"them\".",
		19: "Hand. It could mean arm, apparently, but it also means hand.",
		20: "Then, after, etc.",
		21: "That \"ανάκατ\" part means \"disorderly\" so this means \"cause to become disordered\". It works.",
		22: "This weird lil preposition means like, \"from\". In a <i>lot</i> of senses. Here, due to the meta, it's from in the temporal sense, which is kinda like \"since\".",
		23: "Yep, chronon means year. Chrono means time, but stick an n at the end and you've got \"of time\" which is usually taken to mean year, or age.",
		24: "You've gotta take my word on this, \"μηχανορραφία\" has scheme-y connotations too, just like in English.",
		25: "Cosmos is literally just the Greek word for world.",
		27: "Masculine \"the\".",
		28: "This Greek word is where triumph originated.",
		29: "Bolas unfortunately has that plosive B. We don't have a symbol for that buddy... you're gonna have to accept an MP at the start of your name...",
		30: "To be.",
		31: "Nearby, in quite a lot of contexts."
	},
	"Desolation Twin": {
		1: "There are analagous words for triplets (τρίδυμος) and... possibly others? I'm sure you could just stick the words for four and five and such at the front to construct the other words, but I don't know if they're in any sort of use.",
		2: "This is the noun form of the verb \"ερημώνω\" (erimóno) which means to make desolate. Both words seem to have a lot of connotations with deserts, so one other translation could be like \"desertification.\" Ulamog... kinda does that? I guess?",
		3: "This is an incredibly vague word for a being of some kind. Not necessarily an animal, not necessarily alive, not necessarily physical. \"Ον\" is a similar word that also means a... thing/being/entity. That's the word that WotC used with the most recent Ancient Greek card, but it seems like an obscure word in Modern Greek. \"Ζώο\" (zoh-o) is probably closer to the English \"creature\" but that seems to have a lot less of the versatility that \"creature\" does. Like... that word is just zoo. That's for animals.",
		4: "We get to make up a word today! \"Eldrazi\" obviously gets derived from Eldritch, but fun fact, we don't know where that word came from! It was a word before Lovecraft popularized it, and uses the same root as the word \"else\". Probably. Anyway, this is a proper noun, so let's just spell it phonetically. That means we need an \"ee\" sound at the end, and boy we are spoiled for choice when it comes to that. \"ι\" and \"η\" are the best of the <b>six</b> different vowels/diphtongs that could make that sound, but they come with different gender connotations. Using \"ι\" would be closer to the source material, and come with the nice feature of not assigning a grammatical gender to unknowable space horrors. (Not that MtG doesn't give them <i>actual</i> genders sometimes, but that's a different story. I've got opinions.) In other languages, Eldrazi is a neuter noun when possible, but a masculine noun when that's not possible.",
		5: "Non-interrogative \"when\".",
		6: "I swear, every time I try to find a suitable verb, it's like \"the usual interpretation is this super boring, general thing. But the intended interpretation is a very specific sense of the word.\" but the thing is. Cast literally means throw! We do the exact same thing in English! I <i>think</i> this is a fine verb to use, but it's <i>so</i> hard to research this shit for more specific senses of the word. This one here seems to have a <i>lot</i> of possible meanings.",
		7: "We gotta put a definite article after this in Greek.",
		8: "This is the most generic word for \"magic\" in Greek, and I've decided to use it to mean spell in particular.",
		9: "Again, what a dramatic word. The English \"demiurge\" came from the ancient Greek word for craftsman, \"δημιουργός\". It seems like it evolved into the religious connotation because like, craftsmen create things. God created things.",
		10: "Feminine 'a'.",
		11: "If something is colorless, it is achromatic. Here's where that word came from.",
		12: "I am so unclear on exactly how this whole token phrase should be ordered. Like, the sentence doesn't really make much sense in English, we don't adjective-ify any of the words, despite the fact that they all modify the noun (the word 'token') at the end.",
		13: "Marker. The more common definition of this word is 'brand' as in what type of commercial thing something is. It can also be used to mean an object that is used in place of money in a game. Which is... close. Another good looking word is \"δείγμα\" (digma) which is like, a sample or specimen of a larger concept. \"A token of my love\" and all that. I made a judgement call to use the first option.",
		14: "With. Probably originated from 'meta'.",
		15: "Here's a fun one. The words 'Expensive' and 'Precise' are homophones in Greek, sometimes. Rarely. 'Expensive' is 'ακριβός' and 'Precise' is 'ακριβή'. If coordination were a feminine noun, then for both words we would remove any 'ς' at the end and change the final vowel to a 'η'. So they'd look the same! That doesn't matter in this case because coordination is masculine.",
		16: "Hey look at that coordination has a 'syn' at the beginning because together.",
		17: "And.",
		18: "Adjective meaning 'enough'.",
		19: "This is where the 'hema' in all the blood-related words came from.",
		20: "Similar to the way we use 'that' or 'which' to specify that we want only something that meets a criteria.",
		21: "Neat little feature: You can use has to create perfect tenses! I'm pretty sure I did it right. Perfective aspects are confusing :(",
		22: "This is \"χύνω\" (chino) (to spill) but in the... *clears throat* third person present perfect passive conjugation.",
		23: "Do you think of the word 'can' as a verb? It is! So are would, could, and should! They're something called an auxilliary verb, where we use them in conjunction with another verb to create a more specific meaning. We do the same thing with 'do' when we wanna be affirmative. We <i>do</i> write it that way, which is kinda weird when you think about it.",
		24: "One as in, like, one Eldrazi.",
		25: "Greek doesn't have an infinitive tense (anymore) but it does have this little guy, which lets you create different subjunctives.",
		26: "\"εκδιώχνεται\" = \"εκ\" (out) + \"διώχν(ω)\" (chase away) + \"εται\" (3rd person present imperfect tense). The whole thing means \"be chased outta here\" and appears to be a pretty colloquial word, which is appropriate for the speaker. I chose imperfect because like... they're never really done chasing these guys away, are they?",
		27: "By itself, this is like the \"still\" in \"he's still alive\". It stresses continuation. Here, used with \"και\" it's pretty close to the way \"even\" is used in the sentence. Like \"and still more, it could even be killed!\"",
		28: "And, but used here with the previous word, it's like \"and also!\" stressing the addition.",
		30: "Surprisingly, this word has nothing to do with skeleton. Kill here came from the word for plunging something into darkness, which is sick. Skeleton came from a word meaning parched, or dry. Anyway, I couldn't find a word I was confident meant like \"fell\" or \"bring down\" or similar. I founda  few that seemed close, but I don't know if they carried the meaning Munda here is trying to get across.",
		31: "This is just a preposition that means but.",
		32: "Two is pronounced dio.",
		33: "To be. Here, the subject of the being is the two.",
		34: "Poly means many, believe it or not. Weirdly, you can use it for uncountable things too? We don't do that in English we got much and many for those purposes. It's not that Greek doesn't care about countability, it just doesn't here.",
		35: "Greek does not have an \"uh\" sound. Sorry Munda, you're gonna have to accept this. Technically, the second part of their name would just be a \"d\" sound, so their name is basically just Mooda. Sucks for them, I guess.",
		36: "Leader, or chief. That \"arch\" at the beginning is where we get words like architect, archmage, and even archipelago. Archipelago was the name for the Aegean sea, which is <i>chiefly</i> a sea. (Pelago means sea.)",
		37: "I can't find a good source for this lil tidbit, but I believe this is the ancient Greek word for \"seat\" (ἕδρᾱ) + \"within\" (εν-) like it means to sit in wait perhaps?"
	},
	"Laboratory Maniac": {
		"cr": "So if you want a word for \"creature\" in Greek, your options lie on a spectrum from \"Ζώο\" (animal) to \"Οντότητα\" (entity). The latter portion of that spectrum seems to be really very, very close to the level of vagueness implied by the English \"entity\". Plasma here is a good middle ground, I think. It means creature in what appears to be the same sense as one would say \"All God's creatures\". Also, the word is literally plasma, which does it a few favors.",
		1: "Okay, so this comes from \"εργαστήριο\" (ergastirio) which very visibly comes from just the word for \"job\", \"εργασία\" (ergasia). It could mean workshop, but it could also mean a laboratory. You may notice that laboratory... also has the word labor in it, and the word workshop has the word work in it. Adding the -κός at the end here turns it into an adjective.",
		2: "This word just means maniac, pretty sure that one doesn't require a huge explanation. Look at that literal translation, that's perfect, right? Insane person with a descriptor that just means \"worker\" pretty much? Workaholic. We have a word for that in English, it's great.",
		3: "Alright, fine, taking it a bit more seriously, here's a translation that doesn't preserve word order, but does preserve the meaning a little nicer.",
		4: "Y'know what? You do get an etymology lesson regarding this word: Remember how adding a \"-κός\" makes something an adjective (broadly)? That's how the English word got its \"c\" at the end. The word has retained its \"mania\" + \"kos\" heritage, but dropped the \"os\".",
		5: "Laboratories are neuter, obviously. What kind of weirdo would say that a building has a gender?",
		6: "I don't think I need to explain why anthropos means human. Fun fact: Think about how \"human\" is \"anthro\" but \"man\" (as opposed to woman) is \"andro\". Those words came from the same place, and at some point split like that.",
		7: "Mages are wizards. This language is sorely lacking in magic words.",
		8: "This word is, as best I can tell, incredibly close to English \"if\". It <i>used</i> to be one of Greek's many subjunctive particles, which you'll see more of later in this very translation.",
		9: "There are more than a couple ways to express intention in Greek, and this one is my best guess at one that means \"you're gonna do this, but not like, because you feel like it\".",
		10: "Here's one of those subjunctive particles I was talking about! I've gotten a lot better with these recently, and that's why I wanted to do this card. In this context, it kinda lets you turn a verb into a noun. Like how you can say \"I want to buy candy\" but you can also say \"I want candy\". Both \"to buy candy\" and \"candy\" are treated as nouns.",
		11: "Because this word is in a subjunctive, we gotta conjugate it differently. I finally understand the majority of the conjugation tables for these things... (emphasis on majority).",
		12: "!Feminine accusative \"a\".",
		13: "!Carta means card, not writing that paragraph again.",
		14: "!While.",
		15: "Nominative feminine \"the\". They gave a building a gender...",
		16: "!Library.",
		17: "!\"σου\" doesn't always mean \"of you\", but it does here.",
		18: "!\"Doesn't\" negator.",
		19: "!To have, or in this case, contain.",
		20: "In English, you can say either \"doesn't have any cards\" or \"has no cards\". The closest <i>literal</i> translation in Greek (I know of) is \"έχει μύδεν κάρτεσ\" (has zero cards). That's not very natural, so I opted to instead use this construction.",
		21: "Check out this pronoun babyyy. \"Κανένας\" can mean \"anyone\" or \"anything\" and when used with a \"δεν\" in this way, it flips to mean \"no one\" or \"nothing\". Because of the fact that Greek doesn't distinguish between animate and inanimate nouns like we do, it does all of that.",
		22: "Weirdly, in Greek, using the indefinite pronoun in this way, I <i>think</i> it stays in singular form (like \"doesn't have any card\"). That sounds a little weird in English, but it seems to be how I see it used in Greek.",
		23: "Honestly, why do we even have these words here in English. I'm making the call, these are getting cut in the translation. The verb already has the necessary \"containing\" connotations.",
		24: "You may be aware that the Greek goddess of victory is named Nike (Νίκη, pronounced \"Nee-keh\"). In Greek, the verb \"νικάω\" means to win. But it means win in the sense of like, to prevail! to conquer! to defeat! Not what we're going for. This verb also means to win, but in a less combative sense. It coems from the Greek word for profitting, or benefitting.",
		25: "!Accusative neuter \"the\".",
		26: "This is a noun that can mean either \"game\" or \"toy\". It comes from the same root as \"παιδί\" (paydi) which means child.",
		27: "Yes, this does come from the same place as \"antithesis\" comes from. In Greek, the \"anti\" part just means \"instead of\" or similar (it can also mean opposite). It eventually came to just, only mean opposite as it moved through the rest of Europe. \"Ante-\" is another cognate, and so is just the literal English word \"and\".",
		28: "!Neuter nominative \"the\".",
		29: "Now you might've expected the Greek word for mind to be, like, \"neuro\", or something. Not so. Neuro actually doesn't have anything to do with brains!!! The original Greek word \"νευρο\" (neyro) means nerve. You can see the similarity right there! (It also means penis I have got to mention that.) \"Neurological\" doesn't mean \"pertaining to the science of brains\" it means \"pertaining to the science of nerves\"!",
		30: "!His.",
		31: "To swirl, spin, whirl... y'know. When you strovilizo.",
		32: "Big. I think you can figure out for yourself some times where you've seen \"megalo\" before.",
		33: "This comes from the same place as the word sketch, or scheme.",
		34: "I hate that the word for never is so close to the word for \"when?\" (πότε)",
		35: "To think about something. Compare with \"νομίζω\" which means think in like the opinion/feeling sense. I think that's interesting, and I think about that distinction a lot.",
		36: "!What.",
		37: "This li'l particle indicates that it's future tense.",
		38: "!To be capable of.",
		40: "To happen. It's a combination of \"sym\" (together, like in symmetry or synergy) and \"βαίνω\" (to come/go).",
		42: "!To succeed.",
		43: "!With.",
	}
}